{ pkgs, ... }:
# https://github.com/prettymuchbryce/dotfiles/blob/54d70d7372523b74cafaf88bce5c7e31adcc37d0/modules/system/brave.md
let
  plist = pkgs.formats.plist { };

  bravePolicy = {
    BlockThirdPartyCookies = true;
    BraveAIChatEnabled = false;
    BraveDeAmpEnabled = true;
    BraveDebouncingEnabled = true;
    BraveLeoAssistantEnabled = false;
    BraveNewsDisabled = true;
    BraveP3AEnabled = false;
    BravePlaylistEnabled = false;
    BraveReduceLanguageEnabled = true;
    BraveRewardsDisabled = true;
    BraveSpeedreaderEnabled = false;
    BraveStatsPingEnabled = false;
    BraveTalkDisabled = true;
    BraveVPNDisabled = true;
    BraveWalletDisabled = true;
    BraveWebDiscoveryEnabled = false;
    BrowserSignin = 0;
    DefaultBraveFingerprintingV2Setting = 3;
    DefaultBrowserSettingEnabled = false;
    FeedbackSurveysEnabled = false;
    HttpsOnlyMode = "force_enabled";
    HttpsUpgradesEnabled = true;
    MetricsReportingEnabled = false;
    SafeBrowsingDeepScanningEnabled = false;
    SafeBrowsingExtendedReportingEnabled = false;
    SafeBrowsingSurveysEnabled = false;
    SearchSuggestEnabled = false;
    TorDisabled = true;
    UpdatesSuppressed = true;
    UserFeedbackAllowed = false;
    WebRtcIPHandlingPolicy = "disable_non_proxied_udp";
  };

  bravePolicyProfile = plist.generate "brave.mobileconfig" {
    PayloadContent = [
      {
        PayloadContent = {
          "com.brave.Browser" = {
            Forced = [
              {
                mcx_preference_settings = bravePolicy;
              }
            ];
          };
        };
        PayloadDisplayName = "Brave Browser Policy";
        PayloadEnabled = true;
        PayloadIdentifier = "uk.filo.brave.policy";
        PayloadType = "com.apple.ManagedClient.preferences";
        PayloadUUID = "E7DD6D4D-E784-41F6-B131-3473B6A18C3D";
        PayloadVersion = 1;
      }
    ];
    PayloadDescription = "Managed Brave Browser policy generated by nix-darwin.";
    PayloadDisplayName = "Brave Browser Policy";
    PayloadIdentifier = "uk.filo.brave";
    PayloadOrganization = "filo.uk";
    PayloadRemovalDisallowed = false;
    PayloadScope = "System";
    PayloadType = "Configuration";
    PayloadUUID = "A0936D8D-C8B0-4521-95E9-B8E461126099";
    PayloadVersion = 1;
  };
in
{
  environment.etc."profiles/brave.mobileconfig".source = bravePolicyProfile;
}
