name: update-flake-lock
on:
  workflow_dispatch:
  schedule:
    - cron: '15 8 * * *'

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v20
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
